package paperorgnizer;

import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ItemEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.time.Year;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;

/**
 *
 * @author Hwaipy
 */
public class NewJFrame extends javax.swing.JFrame {

    private final File joirnalListFile = new File("/Users/Hwaipy/Documents/Dropbox/LabWork/Papers/Journals.list");

    /**
     * Creates new form NewJFrame
     *
     * @throws java.io.FileNotFoundException
     */
    public NewJFrame() throws FileNotFoundException, IOException {
        initComponents();

        int currentYear = Year.now().getValue();
        ArrayList<String> years = new ArrayList<>();
        for (int year = currentYear; year > 1900; year--) {
            years.add(year + "");
        }
        jComboBoxYear.setModel(new DefaultComboBoxModel(years.toArray(new String[years.size()])));

        updateJournalList();

        jTextFieldVolumn.setText("");
        jTextFieldPage.setText("");
        jTextFieldAuthor1.setText("");
        jTextFieldAuthor2.setText("");
        jTextFieldTitle.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxYear = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxJournal = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAuthor1 = new javax.swing.JTextField();
        jTextFieldAuthor2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jCheckBoxIsSupplementary = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jTextFieldVolumn = new javax.swing.JTextField();
        jTextFieldPage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Year");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jComboBoxYear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel2.setText("Journal");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jComboBoxJournal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxJournal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxJournalItemStateChanged(evt);
            }
        });
        jComboBoxJournal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJournalActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxJournal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, -1));

        jLabel3.setText("Volumn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Page");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setText("Authors");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jTextFieldAuthor1.setText("jTextField1");
        getContentPane().add(jTextFieldAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 180, -1));

        jTextFieldAuthor2.setText("jTextField3");
        getContentPane().add(jTextFieldAuthor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 180, -1));

        jLabel6.setText("Title");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jTextFieldTitle.setText("jTextField5");
        getContentPane().add(jTextFieldTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 180, -1));

        jCheckBoxIsSupplementary.setText("supplementary");
        getContentPane().add(jCheckBoxIsSupplementary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jButton1.setText("Rename");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jTextFieldVolumn.setText("jTextField1");
        getContentPane().add(jTextFieldVolumn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, -1));

        jTextFieldPage.setText("jTextField2");
        getContentPane().add(jTextFieldPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        StringBuilder sb = new StringBuilder();
        String year = jComboBoxYear.getSelectedItem().toString();
        String journal = jComboBoxJournal.getSelectedItem().toString();
        String volumn = jTextFieldVolumn.getText();
        String page = jTextFieldPage.getText();
        String author1 = jTextFieldAuthor1.getText();
        String author2 = jTextFieldAuthor2.getText();
        String title = jTextFieldTitle.getText();
        boolean isSupplementary = jCheckBoxIsSupplementary.isSelected();

        sb.append(year).append(journal).append(volumn).append(".").append(page)
                .append(" ").append(author1).append(",").append(author2).append("_");
        if (isSupplementary) {
            sb.append("Sup_");
        }
        sb.append(title);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(sb.toString()), null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxJournalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJournalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxJournalActionPerformed

    private void jComboBoxJournalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxJournalItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED && "+".equals(evt.getItem())) {
            try {
                Desktop.getDesktop().open(joirnalListFile);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jComboBoxJournalItemStateChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            updateJournalList();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                NewJFrame frame = new NewJFrame();
                int width = frame.getWidth();
                int height = frame.getHeight();
                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                int x = (screenSize.width - width) / 2;
                int y = (screenSize.height - height) / 2;
                frame.setLocation(x, 0);
                frame.setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    private void updateJournalList() throws FileNotFoundException, IOException {
        BufferedReader reader = new BufferedReader(new FileReader(joirnalListFile));
        ArrayList<String> journals = new ArrayList<>();
        while (true) {
            String journal = reader.readLine();
            if (journal == null || journal.length() == 0) {
                break;
            }
            journals.add(journal);
        }
        journals.add("+");
        jComboBoxJournal.setModel(new DefaultComboBoxModel(journals.toArray(new String[journals.size()])));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBoxIsSupplementary;
    private javax.swing.JComboBox jComboBoxJournal;
    private javax.swing.JComboBox jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldAuthor1;
    private javax.swing.JTextField jTextFieldAuthor2;
    private javax.swing.JTextField jTextFieldPage;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldVolumn;
    // End of variables declaration//GEN-END:variables
}
